version: '3.2'
services:
    web:
        build: .
        ports:
            - "3000:3000"
        expose:
            - "3000"
        links:
            - "mariadb:database"
        depends_on:
            - "mariadb"
        volumes:
            - type: bind
              source: .
              target: /home/ifcomp
              volume:
                  nocopy: true
    mariadb:
        image: mariadb:10.3
        environment:
            MYSQL_DATABASE: 'ifcomp'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
            MYSQL_ROOT_PASSWORD: ''
        ports:
            - "3306:3306"
        expose:
            - "3306"
